# Generated by Django 3.2.4 on 2021-06-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caryard_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='amount',
            field=models.IntegerField(default=3500000),
            preserve_default=False,
        ),
    ]
