# Generated by Django 3.2.4 on 2021-06-23 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caryard_api', '0002_orders_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caryard_api.car'),
        ),
    ]
