# Generated by Django 3.2.4 on 2021-06-23 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caryard_api', '0003_alter_orders_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
